// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/threejs/detector.d.ts
// Type definitions for three.js (Detector.js)
// Project: https://github.com/mrdoob/three.js/blob/master/examples/js/Detector.js
// Definitions by: Satoru Kimura <https://github.com/gyohk>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

interface DetectorStatic {
	canvas: boolean;
	webgl: boolean;
	workers: boolean;
	fileapi: boolean;

	getWebGLErrorMessage(): HTMLElement;
	addGetWebGLMessage(parameters?: {id?: string; parent?: HTMLElement}): void;
}

declare var Detector: DetectorStatic;